### ISSUE TITLE
TypeError: new enumerations must be created as `ClassName([mixin_type,] enumtype)`

### ISSUE THREAD

**Issue by max-the-mage** [10se1ucgo/cue_sdk#12]
Full stacktrace:

```
>>> from cue_sdk import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\retro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cue_sdk\__init__.py", line 1, in <module>
    from .api import *
  File "C:\Users\retro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cue_sdk\api.py", line 7, in <module>
    from .enumerations import *
  File "C:\Users\retro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cue_sdk\enumerations.py", line 45, in <module>
    class CLK(with_metaclass(KeywordMeta, CEnum)):
  File "C:\Users\retro\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 119, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "C:\Users\retro\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 439, in _get_mixins_
    raise TypeError("new enumerations must be created as "
TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)`
```

**Comment by ghost** [comment]
Per https://github.com/10se1ucgo/cue_sdk/issues/9#issuecomment-334954478

Replace with 

class CLK(CEnum, metaclass=KeywordMeta):
and
class CDC(CEnum, metaclass=KeywordMeta):
